//Generated by AntilatencyApiGenerator
#pragma once
#ifndef ANTILATENCY_INTERFACE_CONTRACT_EXCEPTIONS_ENABLED
#define ANTILATENCY_INTERFACE_CONTRACT_EXCEPTIONS_ENABLED
#endif
#include <Antilatency.DeviceNetwork.h>
#include <Antilatency.DeviceNetwork.Interop.h>
#include <Antilatency.Alt.Tracking.h>
#include <Antilatency.Math.h>
#include <Antilatency.IpNetwork.h>
#include <Antilatency.InterfaceContract.Memory.h>
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4946)
#pragma warning(disable: 4265)
#endif

#ifdef _MSC_VER
#pragma warning(pop)
#endif
