//Generated by AntilatencyApiGenerator
#pragma once
#ifndef ANTILATENCY_INTERFACE_CONTRACT_EXCEPTIONS_ENABLED
#define ANTILATENCY_INTERFACE_CONTRACT_EXCEPTIONS_ENABLED
#endif
#ifdef _MSC_VER
#pragma warning(push)
#pragma warning(disable: 4946)
#pragma warning(disable: 4265)
#endif
namespace Antilatency {
	namespace Math {
		struct float3 {
			float x;
			float y;
			float z;
		};
	} //namespace Math
} //namespace Antilatency

namespace Antilatency {
	namespace Math {
		struct floatQ {
			float x;
			float y;
			float z;
			float w;
		};
	} //namespace Math
} //namespace Antilatency

namespace Antilatency {
	namespace Math {
		struct floatP3Q {
			Antilatency::Math::float3 position;
			Antilatency::Math::floatQ rotation;
		};
	} //namespace Math
} //namespace Antilatency


#ifdef _MSC_VER
#pragma warning(pop)
#endif
